apiVersion: skaffold/v1beta13
kind: Config
build:
  local:
    useBuildkit: true
  artifacts:
    - image: pachyderm/pachd
      context: .
      docker:
        dockerfile: Dockerfile-pachd-skaffold
