pipeline:
  name: trigger-kubeflow
transform:
  image: pachyderm/kubeflow_demo_trigger@sha256:46596fc299b9eeff6d9a4e08fd3a00e424e8a75ff22ceb73d2a01223e08d8054
  cmd: [ /bin/trigger.sh ]
  env:
    # PIPELINE_NAME is set in the UI when you create the pipeline. The value in 
    # pipeline.py is not used AFAICT
    PIPELINE_NAME: "mnist_pipeline"
    # Pipeline parameter that sets your pipeline's S3 endpoint
    S3_ENDPOINT_PARAM_NAME: "s3_endpoint" # s3_endpoint is the default--optional
    # The namespace where kubeflow is deployed
    KUBEFLOW_NAMESPACE: "kubeflow" # "kubeflow" is the default--optional
    # Env vars that start with "KF_PARAM_" are passed to the pipeline as
    # parameters
    KF_PARAM_input_bucket: "input"
s3_out: true  # Must be set
input:
  pfs:
    name: input      # Name of the input bucket
    repo: input-repo # Pachyderm repo accessed via this bucket
    glob: /          # Must be exactly this
    s3: true         # Must be set
